import type { Request, Response } from 'express'
import { put, get } from '@vercel/blob'

const PROFILE = 'benchmark-clone-diagnostic-v1'
const BASE = 'benchmark-clone/money-works-v1'

const COMMON = `Create exactly ONE 16:9 horizontal source image for a Korean finance/economy explainer video.
DIAGNOSTIC GOAL: reproduce the visual grammar of the benchmark as closely as possible for diagnostic use, not the normal Economy Grutugi V7 style.
VISUAL STYLE: simple white circular-headed stick-figure worker with thin black line body and small readable facial expression; flat 2D cartoon figure integrated into a semi-realistic cinematic environment; premium Korean YouTube economy explainer/editorial infographic feeling; clean, immediate visual metaphor; not childish.
CHARACTER LOCK: the recurring worker is always the same simple white round-headed stick figure. When capital is personified, use a matching humanoid coworker made from warm gold light and subtle blank asset shapes.
ABSOLUTE SYMBOL BAN: no readable Korean, English, digits, percentages, currency symbols, currency abbreviations, labels, logos, coin engravings, money-bag emblems, signs, subtitles, watermarks or UI anywhere. Represent money/capital only with completely unmarked blue or gold blocks, blank geometric discs, unmarked bars, light, scale, distance and motion. Tracker adds exact text/numbers later.
NO normal V7 finance mascot, no suit-wearing mascot, no photoreal human protagonist, no 3D Pixar character, no candidate sheet, no collage.
MEANING TEST: the economic relationship must be understandable without text within about one second.`

function makePrompt(scene: string, composition: string) {
  return `${COMMON}\nSCENE: ${scene}\nCOMPOSITION: ${composition}`
}

const PANELS: Record<string, { name: string; prompt: string; meaning: string }> = {
  '1': {
    name: 'hook-alone-worker',
    meaning: 'At first only the ordinary worker is working; money has not become a second worker yet.',
    prompt: makePrompt(
      'Late at night, the recurring worker visibly works alone at the LEFT desk. On the RIGHT is an identical empty coworker desk and empty chair reserved for capital. A small inert unmarked asset stack rests motionless nearby. The second work position is clearly empty.',
      'Medium-wide modern office at night, cool navy city lights. Worker in left third, empty second desk in right third, strong negative space on right.'
    )
  },
  '2': {
    name: 'baseline-personal-contribution',
    meaning: 'Early wealth growth comes mostly from the worker repeatedly contributing personal savings.',
    prompt: makePrompt(
      'The recurring worker repeatedly carries equal small cool-blue blank asset blocks from a salary/work side into a transparent investment container. Many blue blocks have accumulated into one large base, while only a tiny warm-gold glow is visible at the edge. The physical action clearly shows that most early growth is coming from the worker adding blocks himself.',
      'Three-quarter view of one integrated scene, worker moving from left to center, large blue accumulated base dominating frame, tiny gold element secondary. Leave clean overlay space above the base.'
    )
  },
  '3': {
    name: 'tiny-capital-return',
    meaning: 'At the beginning, capital return is tiny compared with what the worker personally contributes.',
    prompt: makePrompt(
      'Show a direct size comparison: a very large cool-blue contribution block built by the worker beside a very small warm-gold return block generated by the asset base. The worker looks at the tiny gold block with mild disappointment. No labels or numbers; size difference alone explains the point.',
      'Simple left-right comparison inside one realistic office/investment environment. Blue block occupies about one third of frame height, gold block only a small fraction. Worker placed between them as observer.'
    )
  },
  '4': {
    name: 'compound-mechanism-coworker-born',
    meaning: 'Return is reinvested and becomes part of the base that can generate the next return.',
    prompt: makePrompt(
      'A small warm-gold humanoid capital coworker has just appeared. It picks up a small unmarked gold block created by the existing asset base and places that block back on top of the base. A second faint gold layer begins to glow from the enlarged base, visually showing return feeding the next round of return.',
      'Single integrated side view. Worker watches from left, small gold coworker center-right, stacked asset base right. Use clear hand-to-stack action and a subtle looping light path without arrows or text.'
    )
  },
  '5': {
    name: 'misconception-magic-asset-number',
    meaning: 'There is no single magic total asset amount that universally marks the start of money working for you.',
    prompt: makePrompt(
      'The recurring worker stands confused at a fork with several large unlabeled milestone monuments made of different-sized blank asset stacks. None is visually marked as the correct answer. Behind the worker, a subtle balance relationship between a blue personal-contribution stream and a gold capital-return stream is barely visible, hinting that the real answer is a relationship rather than one monument.',
      'Wide decision-scene with three competing unlabeled asset monuments across the middle distance. Worker foreground center. Keep the visual question clear without signs or digits.'
    )
  },
  '6': {
    name: 'first-coworker-turning-point',
    meaning: 'The worker and capital now contribute at roughly equal strength; money has become the first coworker.',
    prompt: makePrompt(
      'Strong LEFT/RIGHT split. LEFT: dark navy office, the human worker actively works at a desk and pushes one substantial cool-blue blank contribution block forward. RIGHT: warm golden office, a matching gold-light capital coworker actively works and pushes an equally sized completely unmarked gold return block forward. The two sides have equal visual weight. A bright central dividing beam marks the turning point.',
      'Balanced 50/50 split screen in one frame, human and capital coworker equal scale, blue and gold blocks equal size, clean overlay zones above each side.'
    )
  },
  '7': {
    name: 'two-growth-streams-merge',
    meaning: 'From this point, personal contribution and capital return both feed the next stage of growth.',
    prompt: makePrompt(
      'The worker sends a cool-blue stream of blank asset blocks from the left while the gold capital coworker sends an equally strong warm-gold stream from the right. The two streams physically merge at center into one wider rising platform/path that supports the next stage of assets.',
      'Symmetrical V-shaped convergence from left and right into a central broader upward path. Worker and gold coworker small but clearly responsible for each stream.'
    )
  },
  '8': {
    name: 'capital-acceleration-over-time',
    meaning: 'Over time, the worker contribution can stay similar while the capital-return contribution becomes larger.',
    prompt: makePrompt(
      'Create a left-to-right time progression within one continuous scene. Along the path, identical cool-blue contribution blocks from the worker remain roughly the same size at each stage, while warm-gold return blocks from the capital coworker grow from tiny to medium to large. The gold coworker also becomes busier while the worker contribution rhythm stays steady.',
      'Horizontal timeline composition using spatial progression rather than charts or labels. Three or four stages, blue size stable, gold size visibly increasing.'
    )
  },
  '9': {
    name: 'downturn-counterexample',
    meaning: 'Capital does not deliver a smooth guaranteed paycheck; returns can fall or turn negative.',
    prompt: makePrompt(
      'The previously confident gold capital coworker suddenly stumbles as the warm-gold growth path dips sharply downward for one section. Some unmarked gold blocks slide backward or shrink. The recurring worker continues carrying the same cool-blue contribution block forward, surprised but still steady.',
      'One dramatic downturn scene with a clearly visible dip in the gold path, worker steady on left/lower track and gold coworker losing footing on right. No panic clutter.'
    )
  },
  '10': {
    name: 'volatile-coworker',
    meaning: 'The capital coworker is productive but inconsistent; its contribution varies greatly from period to period.',
    prompt: makePrompt(
      'Show the gold capital coworker moving through an uneven sequence of work stations or platforms: one high, one low, one medium, carrying visibly different-sized unmarked gold loads at each. Beside it, the worker moves along a much steadier blue lane carrying similar-sized blue blocks. The comparison should feel like variable performance versus steady personal contribution.',
      'Two parallel lanes across the frame: stable blue worker lane and visibly uneven gold coworker lane with rises and dips. Cinematic depth but simple comparison.'
    )
  },
  '11': {
    name: 'final-criterion-balance',
    meaning: 'The useful milestone is when annual capital return becomes comparable to annual personal contribution.',
    prompt: makePrompt(
      'A large physical balance scale is the central economic metaphor. On the left pan sits one cool-blue blank contribution block placed by the worker. On the right pan sits one warm-gold completely unmarked return block placed by the capital coworker. The scale is nearly perfectly level. The worker and gold coworker stand beside their respective pans at equal scale.',
      'Centered balance scale dominates frame, blue left and gold right, nearly level beam. Characters are supporting actors, not the main subject. Leave clean overlay space above each pan.'
    )
  },
  '12': {
    name: 'final-human-and-money-coworker',
    meaning: 'The worker is no longer the only worker for wealth; money now works alongside the person as a partner.',
    prompt: makePrompt(
      'At sunrise after a long night, the recurring worker and the gold capital coworker stand side by side at equal scale in the foreground, both facing a clear upward road/path of future asset growth. Behind them, a cool-blue path and a warm-gold path merge into one broader rising path toward a bright horizon.',
      'Two figures side by side in lower center with equal visual importance; merged upward path into distance; cool blue and warm gold atmosphere blending at sunrise.'
    )
  }
}

function attemptSuffix(attempt: number) { return attempt <= 1 ? '' : `-attempt-${attempt}` }
function assetPath(panel: string, attempt: number) { return `${BASE}/panel-${panel}${attemptSuffix(attempt)}.bin` }
function metaPath(panel: string, attempt: number) { return `${BASE}/panel-${panel}${attemptSuffix(attempt)}.json` }

function correctedPrompt(panel: string, attempt: number, basePrompt: string, priorReason = '') {
  if (attempt <= 1) return basePrompt
  const observed = String(priorReason || '').trim()
  return `${basePrompt}\n\n[DIAGNOSTIC RETRY — FIX ONLY THE OBSERVED FAILURE]\nPreserve every successful part of the previous composition, character placement, visual metaphor, lighting and exact economic meaning. Fix ONLY the observed failure. ${observed ? `Observed failure: ${observed}` : ''}\nDo not redesign unrelated parts of the scene. The absolute no-readable-text/no-symbol rule still applies.`
}

async function readPrivate(path: string) {
  const result: any = await get(path, { access: 'private', useCache: false })
  if (!result || result.statusCode !== 200 || !result.stream) return null
  return result
}

async function readJson(path: string) {
  const result = await readPrivate(path)
  if (!result) return null
  return JSON.parse(await new Response(result.stream).text())
}

async function fetchJson(url: string, init?: RequestInit) {
  const response = await fetch(url, init)
  const text = await response.text()
  let data: any = null
  try { data = text ? JSON.parse(text) : null } catch {}
  if (!response.ok) throw new Error(data?.error?.message || text || `HTTP ${response.status}`)
  return data
}

export async function handleBenchmarkCloneDiagnostic(req: Request, res: Response) {
  const panel = String((req.query as any)?.panel || '')
  const spec = PANELS[panel]
  if (!spec) return res.status(400).json({ error: { message: 'panel must be 1..12' } })
  const action = String((req.query as any)?.action || 'meta')
  const rawAttempt = Number((req.query as any)?.attempt || 1)
  const attempt = Number.isInteger(rawAttempt) && rawAttempt >= 1 && rawAttempt <= 3 ? rawAttempt : 1
  const priorMeta = attempt > 1 ? await readJson(metaPath(panel, attempt - 1)) : null
  const priorReason = priorMeta?.qc?.retryInstruction || priorMeta?.qc?.reason || ''
  const generationPrompt = correctedPrompt(panel, attempt, spec.prompt, priorReason)

  try {
    if (action === 'asset') {
      const meta = await readJson(metaPath(panel, attempt))
      const asset = await readPrivate(assetPath(panel, attempt))
      if (!asset || !meta) return res.status(404).json({ error: { message: 'stored asset not found' } })
      const buffer = Buffer.from(await new Response(asset.stream).arrayBuffer())
      res.setHeader('Content-Type', meta.mimeType || 'image/png')
      res.setHeader('Content-Length', String(buffer.length))
      res.setHeader('Cache-Control', 'public, max-age=3600')
      return res.status(200).send(buffer)
    }

    const existing = await readJson(metaPath(panel, attempt))
    if (action !== 'generate') {
      return res.status(200).json({ ok: true, panel, attempt, stored: Boolean(existing), meta: existing || null })
    }

    if (existing) return res.status(200).json({ ok: true, panel, attempt, stored: true, reused: true, meta: existing })

    const host = String(req.headers.host || 'shorts-tracker-v4-proxy.vercel.app')
    const origin = `https://${host}`
    const imageData = await fetchJson(`${origin}/api/image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({
        contractVersion: '1.5', taskType: 'cut_image', providerId: 'gemini', modelId: 'gemini-3.1-flash-image',
        input: { prompt: generationPrompt, aspectRatio: '16:9', imageSize: '1K', cutIndex: Number(panel) - 1, references: [], profile: PROFILE }
      })
    })

    const base64 = String(imageData?.image?.base64 || imageData?.imageBase64 || imageData?.base64 || '').replace(/^data:[^;]+;base64,/, '')
    const mimeType = String(imageData?.image?.mimeType || imageData?.mimeType || 'image/png')
    if (!base64) throw new Error('Gemini image payload missing')
    const buffer = Buffer.from(base64, 'base64')

    await put(assetPath(panel, attempt), buffer, { access: 'private', allowOverwrite: false, addRandomSuffix: false, contentType: mimeType })

    let qc: any = null
    let qcError: string | null = null
    try {
      qc = await fetchJson(`${origin}/api/gpt-image-qc`, {
        method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify({ input: {
          prompt: generationPrompt, imageBase64: base64, mimeType,
          context: { profile: PROFILE, panel, attempt, panelName: spec.name, viewerMustUnderstand: spec.meaning, economyLongformV01: false, benchmarkCloneDiagnostic: true, zeroTextBaseImage: true }
        } })
      })
    } catch (err: any) { qcError = err?.message || String(err) }

    const meta = {
      schemaVersion: 'BENCHMARK-CLONE-ASSET-1', profile: PROFILE, panel, attempt, panelName: spec.name,
      viewerMustUnderstand: spec.meaning, generatedAt: new Date().toISOString(), provider: 'gemini', model: 'gemini-3.1-flash-image',
      mimeType, byteLength: buffer.length, requestId: imageData?.meta?.requestId || null,
      qc, qcError, retryCount: attempt - 1, autoRetry: false,
      retryReason: attempt > 1 ? priorReason : null,
      assetEndpoint: `/api/image?diagnostic=benchmark-clone&panel=${panel}&attempt=${attempt}&action=asset`
    }
    await put(metaPath(panel, attempt), JSON.stringify(meta), { access: 'private', allowOverwrite: false, addRandomSuffix: false, contentType: 'application/json', cacheControlMaxAge: 60 })
    return res.status(200).json({ ok: true, panel, attempt, stored: true, reused: false, meta })
  } catch (err: any) {
    console.error('[BENCHMARK_CLONE_DIAGNOSTIC]', JSON.stringify({ panel, attempt, action, error: err?.message || String(err) }))
    return res.status(500).json({ error: { message: err?.message || String(err) } })
  }
}
