import test from 'node:test';import assert from 'node:assert/strict';import {referenceAssetId,REFERENCE_AXES} from '../lib/reference/contracts.js';import {analyzeReferenceDeterministic,referenceAnalysisHash} from '../lib/reference/analyzer.js'
const sha='b'.repeat(64);const asset:any={schema:'reference-asset/1',referenceAssetId:referenceAssetId(sha),kind:'video',sha256:sha,bytes:10,contentType:'video/mp4',blobPath:'references/x',width:1080,height:1920,duration:12,createdAt:'x'}
test('analyzer emits all eight evidence-backed axes deterministically',()=>{const s={duration:12,width:1080,height:1920,hasAudio:true,sceneRanges:[{start:0,end:2},{start:2,end:5}],highlights:[{start:2,end:4,score:.9}],silentRanges:[{start:8,end:9}],narrationRanges:[{start:.5,end:1.5}]};const a=analyzeReferenceDeterministic(asset,s);assert.deepEqual(new Set(a.features.map(x=>x.axis)),new Set(REFERENCE_AXES));assert.ok(a.features.every(x=>x.evidence.length&&x.appliesTo.length));assert.equal(referenceAnalysisHash(a),referenceAnalysisHash(analyzeReferenceDeterministic(asset,s)))})
test('still reference emits eight axes but intrinsic temporal/audio semantics are not applicable',()=>{const x={...asset,kind:'screenshot',duration:undefined,width:720,height:1280};const a=analyzeReferenceDeterministic(x,{width:720,height:1280,captionRegions:[{x:.1,y:.7,width:.8,height:.2}]});assert.equal(a.features.length,8);assert.ok(a.features.every(x=>x.evidence[0].kind==='region'));for(const id of ['story.opening','retention.peak','editing.cadence','sound.structure','narration.structure']){const feature:any=a.features.find(x=>x.id===id);assert.equal(feature.value.status,'not_applicable',id)};assert.equal((a.features.find(x=>x.id==='sound.structure')!.value as any).hasAudio,null);assert.equal((a.features.find(x=>x.id==='editing.cadence')!.value as any).meanSceneSeconds,null)})

test('temporal targets use measured reference signals and full duration',()=>{const s={duration:12,width:1080,height:1920,hasAudio:true,sceneRanges:[{start:0,end:2.4},{start:2.4,end:5}],highlights:[{start:6,end:7,score:.9}],silentRanges:[{start:8,end:9}],narrationRanges:[{start:1,end:4}]};const a=analyzeReferenceDeterministic(asset,s);const story:any=a.features.find(x=>x.id==='story.opening')!.value,ret:any=a.features.find(x=>x.id==='retention.peak')!.value,nar:any=a.features.find(x=>x.id==='narration.structure')!.value;assert.equal(story.openingSeconds,2.4);assert.equal(story.duration,12);assert.deepEqual(ret.firstPeak,{start:6,end:7,score:.9});assert.equal(ret.duration,12);assert.equal(nar.duration,12);assert.equal(nar.scope,'non-silent-audio-activity')})
test('missing measured highlight remains unknown instead of inventing a retention peak',()=>{const a=analyzeReferenceDeterministic(asset,{duration:12,width:1080,height:1920,sceneRanges:[{start:0,end:2}]});const ret:any=a.features.find(x=>x.id==='retention.peak')!.value;assert.equal(ret.status,'unknown');assert.equal(ret.firstPeak,null)})

test('reference canvas geometry is evidence, not an impossible fixed-output style/composition constraint',()=>{const x={...asset,kind:'screenshot',duration:undefined,width:1080,height:2340};const a=analyzeReferenceDeterministic(x,{width:1080,height:2340,captionRegions:[{x:.1,y:.7,width:.8,height:.1}]});for(const id of ['visual.style','composition.frame'])assert.equal((a.features.find(f=>f.id===id)!.value as any).status,'not_applicable')})

test('measured single-take video marks opening/cadence not-applicable instead of poisoning conformance with UNKNOWN',()=>{const x=analyzeReferenceDeterministic(asset,{duration:20,width:576,height:1024,sceneRanges:[{start:0,end:20}]});for(const id of ['story.opening','editing.cadence'])assert.equal((x.features.find(f=>f.id===id)!.value as any).status,'not_applicable')})
test('missing scene measurement remains UNKNOWN and fail-closed',()=>{const x=analyzeReferenceDeterministic(asset,{duration:20,width:576,height:1024});for(const id of ['story.opening','editing.cadence'])assert.equal((x.features.find(f=>f.id===id)!.value as any).status,'unknown')})
