import test from 'node:test';import assert from 'node:assert/strict';import {evaluateReferenceConformance} from '../lib/reference/qc.js'
const sha='a'.repeat(64),rh='b'.repeat(64)
const profile:any={schema:'reference-profile/1',profileVersion:'reference-profile/1',referenceAssetIds:['ref_'+sha],constraints:[{id:'ref_'+sha+':editing.cadence',axis:'editing',value:{meanSceneSeconds:2},confidence:1,evidence:[{kind:'time',start:0,end:4}],appliesTo:['PLAN','RENDER','QC']}],createdAt:'2026-09-30T00:00:00Z'}
test('PLAN applied evidence alone cannot PASS cadence conformance',()=>{const r=evaluateReferenceConformance(profile,{planReference:{applied:[profile.constraints[0].id]},measurements:{}});assert.equal(r.decision,'BLOCK');assert.equal(r.checks[0].status,'UNKNOWN')})
test('trusted render-byte cadence measurement can PASS',()=>{const id=profile.constraints[0].id,m:any={measured:true,pass:true,target:{meanSceneSeconds:2},actual:{meanSceneSeconds:2.2,sceneCuts:8},tolerance:{seconds:1},method:'ffmpeg-scene-score-output-cadence',provenance:{source:'server-render-bytes',renderHash:rh,bytesHash:sha}};const r=evaluateReferenceConformance(profile,{measurements:{[id]:m}});assert.equal(r.decision,'PASS');assert.equal(r.checks[0].status,'PASS')})
test('self-attested cadence without render-byte provenance remains UNKNOWN',()=>{const id=profile.constraints[0].id,m:any={measured:true,pass:true,target:2,actual:2,method:'claimed',provenance:{source:'client',renderHash:rh,bytesHash:sha}};const r=evaluateReferenceConformance(profile,{measurements:{[id]:m}});assert.equal(r.decision,'BLOCK');assert.equal(r.checks[0].status,'UNKNOWN')})

test('full eight-axis ReferenceProfile cannot report PASS when only currently implemented render-byte measurements exist',()=>{const axes:any[]=[['story.opening','story'],['retention.peak','retention'],['editing.cadence','editing'],['visual.style','visualStyle'],['composition.frame','composition'],['caption.layout','caption'],['sound.structure','sound'],['narration.structure','narration']];const p:any={schema:'reference-profile/1',profileVersion:1,referenceAssetIds:['ref_'+sha],sourceAnalysisHashes:[sha],constraints:axes.map(([fid,axis])=>({id:'ref_'+sha+':'+fid,axis,value:{},evidence:[{kind:'time',start:0,end:4}],appliesTo:['QC']}))};const measuredIds=['editing.cadence','composition.frame','sound.structure'];const measurements:any={};for(const fid of measuredIds){const id='ref_'+sha+':'+fid;measurements[id]={measured:true,pass:true,target:{},actual:{},method:'server-output-test',provenance:{source:'server-render-bytes',renderHash:rh,bytesHash:sha}}}const r=evaluateReferenceConformance(p,{measurements});assert.equal(r.decision,'BLOCK');assert.equal(r.checks.filter((x:any)=>x.status==='PASS').length,3);assert.equal(r.checks.filter((x:any)=>x.status==='UNKNOWN').length,5)})

test('visual style geometry requires trusted final-render measurement, never PLAN evidence',()=>{const id='ref_'+sha+':visual.style',p:any={schema:'reference-profile/1',profileVersion:1,referenceAssetIds:['ref_'+sha],sourceAnalysisHashes:[sha],constraints:[{id,axis:'visualStyle',value:{orientation:'portrait',aspectRatio:.5625,status:'measured',scope:'geometric-style'},evidence:[{kind:'time',start:0,end:4}],appliesTo:['RENDER','QC']}]};const claimed=evaluateReferenceConformance(p,{renderEvidence:{[id]:{measured:true,pass:true,target:{},actual:{},method:'claimed',provenance:{source:'plan',renderHash:rh,bytesHash:sha}}}});assert.equal(claimed.decision,'BLOCK');const measured=evaluateReferenceConformance(p,{measurements:{[id]:{measured:true,pass:true,target:{orientation:'portrait',aspectRatio:.5625},actual:{orientation:'portrait',aspectRatio:.5625},method:'ffmpeg-probe-output-geometric-style',provenance:{source:'server-render-bytes',renderHash:rh,bytesHash:sha}}}});assert.equal(measured.decision,'PASS')})

test('story opening requires trusted final render measurement',()=>{const id='ref_'+sha+':story.opening',p:any={schema:'reference-profile/1',profileVersion:1,referenceAssetIds:['ref_'+sha],sourceAnalysisHashes:[sha],constraints:[{id,axis:'story',value:{openingSeconds:3},evidence:[{kind:'time',start:0,end:3}],appliesTo:['PLAN','QC']}]};assert.equal(evaluateReferenceConformance(p,{planReference:{applied:[id]}}).decision,'BLOCK');const m:any={measured:true,pass:true,target:{openingSeconds:3},actual:{firstSceneBoundary:2.8},method:'ffmpeg-scene-score-output-opening-boundary',provenance:{source:'server-render-bytes',renderHash:rh,bytesHash:sha}};assert.equal(evaluateReferenceConformance(p,{measurements:{[id]:m}}).decision,'PASS')})

test('retention peak requires trusted final render signal measurement',()=>{const id='ref_'+sha+':retention.peak',p:any={schema:'reference-profile/1',profileVersion:1,referenceAssetIds:['ref_'+sha],sourceAnalysisHashes:[sha],constraints:[{id,axis:'retention',value:{firstPeak:{start:4,end:6}},evidence:[{kind:'time',start:4,end:6}],appliesTo:['PLAN','QC']}]};assert.equal(evaluateReferenceConformance(p,{planReference:{applied:[id]}}).decision,'BLOCK');const m:any={measured:true,pass:true,target:{firstPeakNormalized:.25},actual:{firstPeakNormalized:.28},method:'ffmpeg-signals-output-retention-peak',provenance:{source:'server-render-bytes',renderHash:rh,bytesHash:sha}};assert.equal(evaluateReferenceConformance(p,{measurements:{[id]:m}}).decision,'PASS')})

test('caption layout requires trusted final render layout measurement',()=>{const id='ref_'+sha+':caption.layout',p:any={schema:'reference-profile/1',profileVersion:1,referenceAssetIds:['ref_'+sha],sourceAnalysisHashes:[sha],constraints:[{id,axis:'caption',value:{coverage:{x:.1,y:.7,width:.8,height:.12}},evidence:[{kind:'region',x:.1,y:.7,width:.8,height:.12}],appliesTo:['RENDER','QC']}]};assert.equal(evaluateReferenceConformance(p,{renderEvidence:{[id]:{pass:true}}}).decision,'BLOCK');const m:any={measured:true,pass:true,target:{centerY:.76},actual:{centerY:.78},method:'libass-rendered-overlay-events+final-render-bytes',provenance:{source:'server-render-bytes',renderHash:rh,bytesHash:sha}};assert.equal(evaluateReferenceConformance(p,{measurements:{[id]:m}}).decision,'PASS')})
