import test from 'node:test';import assert from 'node:assert/strict';import {buildReferenceProductionBrief,planReferenceConstraints,renderReferenceConstraints,qcReferenceConstraints} from '../lib/reference/profile.js'
const ev=[{kind:'time',start:0,end:1}]
const axes:any[]=[['p','story',['PLAN']],['ret','retention',['PLAN','QC']],['edit','editing',['PLAN','RENDER','QC']],['style','visualStyle',['RENDER','QC']],['r','composition',['RENDER','QC']],['cap','caption',['RENDER','QC']],['snd','sound',['PLAN','RENDER','QC']],['nar','narration',['PLAN','RENDER','QC']]]
const a:any={schema:'reference-analysis/1',analyzerVersion:'reference-analyzer/2',referenceAssetId:'ref_'+ 'a'.repeat(64),referenceSha256:'a'.repeat(64),features:axes.map(([id,axis,appliesTo])=>({id,axis,value:1,evidence:ev,appliesTo}))}
test('production brief routes complete eight-axis constraints without changing existing profile name',()=>{const x=buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[a]});assert.equal(x.brief.profile,'source_shorts');assert.equal(x.profile.constraints.length,8);assert.ok(planReferenceConstraints(x.brief).length>=1);assert.ok(renderReferenceConstraints(x.brief).length>=1);assert.ok(qcReferenceConstraints(x.brief).length>=1);assert.match(x.profileHash,/^[a-f0-9]{64}$/)})

test('three-reference profile is deterministic regardless of input order and keeps one-to-one provenance',()=>{const mk=(ch:string)=>({...a,referenceAssetId:'ref_'+ch.repeat(64),referenceSha256:ch.repeat(64)});const aa=mk('a'),bb=mk('b'),cc=mk('c');const x=buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[aa,bb,cc]});const y=buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[cc,aa,bb]});assert.equal(x.profileHash,y.profileHash);assert.deepEqual(x.profile.referenceAssetIds,y.profile.referenceAssetIds);assert.equal(new Set(x.profile.referenceAssetIds).size,3);assert.equal(x.profile.constraints.filter(c=>c.id==='aggregate:editing.cadence').length,1);assert.equal(x.profile.constraints.filter(c=>c.id==='aggregate:story.opening').length,1);assert.equal(x.profile.constraints.filter(c=>c.id==='aggregate:retention.peak').length,1)})

test('duplicate reference analyses cannot masquerade as multiple independent references',()=>{assert.throws(()=>buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[a,a,a]}),/duplicate reference/i)})

test('mixed media does not turn intrinsically unmeasurable axes into permanent QC blockers',()=>{const still:any={...a,referenceAssetId:'ref_'+ 'd'.repeat(64),referenceSha256:'d'.repeat(64),features:a.features.map((f:any)=>['story','retention','editing','sound','narration','visualStyle','composition'].includes(f.axis)?{...f,value:{status:'not_applicable'},evidence:[{kind:'region',x:0,y:0,width:1,height:1}]}:{...f,evidence:[{kind:'region',x:0,y:0,width:1,height:1}]})};const x=buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[a,still]});assert.equal(x.profile.constraints.some((c:any)=>c.id.startsWith(still.referenceAssetId+':')&&['story','retention','editing','sound','narration'].includes(c.axis)),false);assert.equal(x.profile.constraints.some((c:any)=>c.id.startsWith(still.referenceAssetId+':')&&c.axis==='composition'),false)})

test('conflicting multi-reference cadence is synthesized to the same single median target used by PLAN/QC',()=>{const mk=(ch:string,cad:number)=>({...a,referenceAssetId:'ref_'+ch.repeat(64),referenceSha256:ch.repeat(64),features:a.features.map((f:any)=>f.id==='edit'?{...f,value:{meanSceneSeconds:cad,status:'measured'}}:{...f,value:{...(typeof f.value==='object'?f.value:{}),status:'measured'}})});const x=buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[mk('a',1.5),mk('b',4)]});const q:any=x.profile.constraints.find(c=>c.id==='aggregate:editing.cadence');assert.equal(q.value.meanSceneSeconds,2.75);assert.equal(x.profile.constraints.some(c=>c.id.endsWith(':editing.cadence')),false)})

test('unknown measurement failure is preserved as a blocking profile constraint',()=>{const bad:any={...a,referenceAssetId:'ref_'+ 'e'.repeat(64),referenceSha256:'e'.repeat(64),features:a.features.map((f:any)=>f.axis==='caption'?{...f,value:{status:'unknown',reason:'provider failed'}}:f)};const x=buildReferenceProductionBrief({profile:'source_shorts',sourceAssetId:'src_x',analyses:[bad]});assert.ok(x.profile.constraints.some((c:any)=>c.axis==='caption'&&(c.value as any).status==='unknown'))})
