import test from 'node:test';import assert from 'node:assert/strict';import {applyReferencePlanConstraints} from '../lib/reference/planBridge.js'
const ev={kind:'time' as const,start:0,end:4}
test('reference cadence changes real beats without changing covered source time',()=>{const variants:any=[{id:'v1',label:'x',rationale:'base',beats:[{label:'cause',trimStart:2,trimEnd:10},{label:'payoff',trimStart:12,trimEnd:16}]}];const c:any=[{id:'ref_x:editing.cadence',axis:'editing',value:{meanSceneSeconds:2},confidence:1,evidence:[ev],appliesTo:['PLAN']}];const r=applyReferencePlanConstraints(variants,c);assert.ok(variants[0].beats.length>2);assert.equal(variants[0].beats[0].trimStart,2);assert.equal(variants[0].beats.at(-1).trimEnd,16);assert.ok(r.changes[0].afterBeats>r.changes[0].beforeBeats)})
test('reference opening creates a real first-beat boundary but never moves causal start',()=>{const variants:any=[{id:'v1',label:'x',rationale:'base',beats:[{label:'cause',trimStart:5,trimEnd:12},{label:'payoff',trimStart:12,trimEnd:16}]}];const c:any=[{id:'ref_x:story.opening',axis:'story',value:{openingSeconds:2},confidence:1,evidence:[ev],appliesTo:['PLAN']}];applyReferencePlanConstraints(variants,c);assert.equal(variants[0].beats[0].trimStart,5);assert.equal(variants[0].beats[0].trimEnd,7);assert.equal(variants[0].beats[1].trimStart,7)})

test('PLAN never reports applied when a valid reference constraint makes no real mutation',()=>{const variants:any=[{id:'v1',label:'x',rationale:'base',beats:[{label:'cause',trimStart:0,trimEnd:2}]}];const c:any=[{id:'ref_x:editing.cadence',axis:'editing',value:{meanSceneSeconds:3},evidence:[ev],appliesTo:['PLAN']},{id:'ref_x:retention.peak',axis:'retention',value:{firstPeak:{start:1,end:2}},evidence:[ev],appliesTo:['PLAN']},{id:'ref_x:sound.structure',axis:'sound',value:{status:'measured',hasAudio:true},evidence:[ev],appliesTo:['PLAN']}];const r=applyReferencePlanConstraints(variants,c);assert.deepEqual(r.applied,[]);assert.equal(r.changes.length,0);assert.deepEqual(new Set(r.unknown),new Set(c.map((x:any)=>x.id)));assert.doesNotMatch(variants[0].rationale,/reference-conditioned/)})

test('multiple cadence references are order-independent and do not sequentially over-split',()=>{const make=()=>[{id:'v1',label:'x',rationale:'base',beats:[{label:'cause',trimStart:0,trimEnd:8}]}] as any;const a:any={id:'ref_a:editing.cadence',axis:'editing',value:{meanSceneSeconds:2},evidence:[ev],appliesTo:['PLAN']},b:any={id:'ref_b:editing.cadence',axis:'editing',value:{meanSceneSeconds:4},evidence:[ev],appliesTo:['PLAN']};const v1=make(),v2=make();applyReferencePlanConstraints(v1,[a,b]);applyReferencePlanConstraints(v2,[b,a]);assert.deepEqual(v1[0].beats,v2[0].beats);assert.ok(v1[0].beats.length<=4)})

test('cadence splitting preserves each original source interval exactly with no rounding gaps or overlaps',()=>{const original=[{label:'a',trimStart:0.13,trimEnd:7.97},{label:'b',trimStart:9.11,trimEnd:14.89}];const variants:any=[{id:'v1',label:'x',rationale:'base',beats:original.map(x=>({...x}))}];const c:any=[{id:'ref_x:editing.cadence',axis:'editing',value:{meanSceneSeconds:1.37},evidence:[ev],appliesTo:['PLAN']}];applyReferencePlanConstraints(variants,c);for(const src of original){const xs=variants[0].beats.filter((b:any)=>b.trimStart>=src.trimStart&&b.trimEnd<=src.trimEnd);assert.equal(xs[0].trimStart,src.trimStart);assert.equal(xs.at(-1).trimEnd,src.trimEnd);for(let i=1;i<xs.length;i++)assert.equal(xs[i-1].trimEnd,xs[i].trimStart);const covered=xs.reduce((n:number,b:any)=>n+b.trimEnd-b.trimStart,0);assert.ok(Math.abs(covered-(src.trimEnd-src.trimStart))<1e-9)}})
test('opening split preserves exact first-beat coverage at fractional boundaries',()=>{const variants:any=[{id:'v1',label:'x',rationale:'base',beats:[{label:'cause',trimStart:.13,trimEnd:7.97}]}];const c:any=[{id:'ref_x:story.opening',axis:'story',value:{openingSeconds:2.345},evidence:[ev],appliesTo:['PLAN']}];applyReferencePlanConstraints(variants,c);assert.equal(variants[0].beats[0].trimStart,.13);assert.equal(variants[0].beats.at(-1).trimEnd,7.97);assert.equal(variants[0].beats[0].trimEnd,variants[0].beats[1].trimStart);assert.ok(Math.abs(variants[0].beats.reduce((n:number,b:any)=>n+b.trimEnd-b.trimStart,0)-(7.97-.13))<1e-9)})
