import test from 'node:test';import assert from 'node:assert/strict';import {evaluateReferenceConformance} from '../lib/reference/qc.js';import {conformanceReport,validateReferenceProfile} from '../lib/reference/contracts.js'
const h='a'.repeat(64),rh='b'.repeat(64)
const p:any={schema:'reference-profile/1',profileVersion:1,referenceAssetIds:['ref_'+h],sourceAnalysisHashes:[h],constraints:[{id:'story.opening',axis:'story',value:{openingSeconds:3},evidence:[{kind:'time',start:0,end:3}],appliesTo:['PLAN']},{id:'composition.frame',axis:'composition',value:{orientation:'portrait'},evidence:[{kind:'region',x:0,y:0,width:1,height:1}],appliesTo:['RENDER','QC']}]}
const prov={source:'server-render-bytes',renderHash:rh,bytesHash:h}
test('consuming a PLAN constraint is not conformance proof',()=>{const r=evaluateReferenceConformance(p,{planReference:{applied:['story.opening']}});assert.equal(r.decision,'BLOCK');assert.equal(r.checks.find((x:any)=>x.featureId==='story.opening')!.status,'UNKNOWN')})
test('unmeasured render evidence cannot satisfy conformance',()=>{const r=evaluateReferenceConformance(p,{renderEvidence:{'composition.frame':{orientation:'portrait'}}});assert.equal(r.decision,'BLOCK')})
test('self-attested measured pass without trusted provenance is UNKNOWN',()=>{const r=evaluateReferenceConformance(p,{measurements:{'composition.frame':{measured:true,pass:true,target:'portrait',actual:'portrait',method:'fake'}}});assert.equal(r.checks.find((x:any)=>x.featureId==='composition.frame')!.status,'UNKNOWN');assert.equal(r.decision,'BLOCK')})
test('trusted independent target-vs-output measurement can pass checks',()=>{const m={measured:true,pass:true,target:'portrait',actual:'portrait',method:'ffmpeg-probe-output-orientation',provenance:prov};const r=evaluateReferenceConformance(p,{measurements:{'story.opening':{...m,target:3,actual:3},'composition.frame':m}});assert.equal(r.decision,'PASS')})
test('trusted measured mismatch fails',()=>{const r=evaluateReferenceConformance(p,{measurements:{'composition.frame':{measured:true,pass:false,target:'portrait',actual:'landscape',method:'ffmpeg-probe-output-orientation',provenance:prov}}});assert.equal(r.checks.find((x:any)=>x.featureId==='composition.frame')!.status,'FAIL');assert.equal(r.decision,'BLOCK')})
test('empty conformance checks never pass',()=>{const empty:any={...p,constraints:[]};assert.equal(conformanceReport(empty,[]).decision,'BLOCK')})
test('profile validator rejects empty or incomplete axis coverage',()=>{assert.ok(validateReferenceProfile({...p,constraints:[]}).length);assert.ok(validateReferenceProfile(p).some(x=>x.startsWith('missingAxis:')))})
test('profile validator handles null safely',()=>{assert.deepEqual(validateReferenceProfile(null),['profile'])})
