import type { Request, Response } from 'express'

function setCors(_req: Request, res: Response) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept')
  res.setHeader('Cache-Control', 'no-store')
}

function extractText(data: any) {
  if (typeof data?.output_text === 'string') return data.output_text.trim()
  for (const item of data?.output || []) {
    for (const content of item?.content || []) {
      if (typeof content?.text === 'string') return content.text.trim()
    }
  }
  return ''
}

const QC_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: [
    'decision',
    'semanticMatch',
    'defects',
    'reason',
    'retryInstruction',
    'confidence'
  ],
  properties: {
    decision: { type: 'string', enum: ['PASS', 'RETRY'] },
    semanticMatch: { type: 'boolean' },
    defects: {
      type: 'object',
      additionalProperties: false,
      required: [
        'generatedText',
        'missingOrBrokenFace',
        'characterStyleBreak',
        'realHumanProtagonist',
        'brokenAnatomy',
        'blankCanvas',
        'irrelevantMeaning',
        'badComposition',
        'mascotMissingOrWrongCount',
        'styleFloorFailure',
        'wrongOrientation'
      ],
      properties: {
        generatedText: { type: 'boolean' },
        missingOrBrokenFace: { type: 'boolean' },
        characterStyleBreak: { type: 'boolean' },
        realHumanProtagonist: { type: 'boolean' },
        brokenAnatomy: { type: 'boolean' },
        blankCanvas: { type: 'boolean' },
        irrelevantMeaning: { type: 'boolean' },
        badComposition: { type: 'boolean' },
        mascotMissingOrWrongCount: { type: 'boolean' },
        styleFloorFailure: { type: 'boolean' },
        wrongOrientation: { type: 'boolean' }
      }
    },
    reason: { type: 'string' },
    retryInstruction: { type: 'string' },
    confidence: { type: 'integer', minimum: 0, maximum: 100 }
  }
} as const

export default async function handler(req: Request, res: Response) {
  setCors(req, res)
  if (req.method === 'OPTIONS') return res.status(204).end()

  if (req.method === 'GET') {
    return res.status(200).json({
      ok: Boolean(process.env.OPENAI_API_KEY),
      provider: 'OpenAI',
      model: process.env.OPENAI_VISION_MODEL || process.env.OPENAI_MODEL || 'gpt-5-mini',
      contractVersion: 'gpt-vision-qc-v1.1'
    })
  }

  if (req.method !== 'POST') return res.status(405).json({ error: { message: 'Method not allowed' } })
  if (!process.env.OPENAI_API_KEY) {
    return res.status(503).json({ error: { message: 'OPENAI_API_KEY is not configured' } })
  }

  const input = req.body?.input || {}
  const prompt = String(input.prompt || '').trim()
  const imageBase64 = String(input.imageBase64 || '').replace(/^data:[^;]+;base64,/, '')
  const mimeType = String(input.mimeType || 'image/png').trim() || 'image/png'
  const context = input.context && typeof input.context === 'object' ? input.context : {}
  const economyLongform = context?.economyLongformV01 === true || String(context?.profile || '') === 'economy-longform-v01'

  if (!prompt) return res.status(400).json({ error: { message: 'prompt is required' } })
  if (!imageBase64) return res.status(400).json({ error: { message: 'imageBase64 is required' } })

  const instructions = [
    'You are the independent Vision QC reviewer for a Korean YouTube production pipeline.',
    'The image was generated by Gemini. You are NOT the generator. Judge it independently.',
    'Do not use a numeric aesthetic score as the main decision. PASS only when the image can safely be used for this CUT.',
    '',
    '[Priority order]',
    '1. Semantic match: does the image explain the exact CUT meaning, not a neighboring or generic economy concept?',
    '2. Hard defects: broken/nonsense generated text, missing/broken primary face, style break, photoreal human replacing required channel character, broken anatomy, accidental blank poster/card, clearly irrelevant meaning.',
    '3. Composition: the main relation should be understandable quickly and should leave safe space for Tracker overlay when requested.',
    '',
    '[Text rule]',
    'Tracker may later add exact Korean text/numbers as deterministic overlay. Treat prominent unintended text or nonsense text inside the generated artwork as a defect.',
    'Do not fail tiny incidental details on money or props unless they are prominent or misleading.',
    '',
    ...(economyLongform ? [
      '[ECONOMY LONGFORM V0.1 — HARD QC GATES]',
      'This path has three additional non-negotiable hard gates.',
      'A. MASCOT COUNT: the image must contain exactly ONE clearly visible professional finance mascot: round pale face, clean dark outline, simple readable eyes/mouth, navy suit, white shirt, roughly 8–10% of frame. If there is zero mascot, more than one mascot, a stick figure, Gru/SD character, toy child character, or a photoreal human protagonist replacing the mascot, set mascotMissingOrWrongCount=true and decision=RETRY.',
      'Background population silhouettes are allowed only when semantically necessary and visually subordinate; they do not count as the finance mascot.',
      'B. STYLE FLOOR: the frame must read as premium Korean finance editorial / cinematic finance documentary with refined semi-realistic 2.5D depth, integrated environment, deep navy + warm amber/orange + controlled red, rich but organized detail. If it looks like cheap vector, flat infographic, PowerPoint/card-news, children educational art, toy-like glossy 3D, generic stock illustration, or simplistic animation, set styleFloorFailure=true and decision=RETRY.',
      'C. ORIENTATION: the final artwork must be a single horizontal 16:9 long-form composition. If it is portrait/vertical, square, a candidate sheet, or clearly non-horizontal, set wrongOrientation=true and decision=RETRY.',
      'The economic relationship/metaphor must remain the main subject. Mascot is a supporting explainer, not the main subject.',
      ''
    ] : []),
    '[Decision rule]',
    'If ANY hard defect is clearly present, decision=RETRY.',
    'If semanticMatch=false, decision=RETRY.',
    'For economy longform, mascotMissingOrWrongCount=true OR styleFloorFailure=true OR wrongOrientation=true always means RETRY.',
    'Otherwise PASS unless composition is so poor that the intended meaning cannot be understood.',
    'For RETRY, write a short retryInstruction that preserves good parts and fixes only the failure.',
    'Return JSON only.'
  ].join('\n')

  const contentText = [
    '[CUT generation prompt / semantic target]',
    prompt,
    '',
    '[Structured CUT context]',
    JSON.stringify(context)
  ].join('\n')

  const model = String(process.env.OPENAI_VISION_MODEL || process.env.OPENAI_MODEL || 'gpt-5-mini')

  try {
    const response = await fetch('https://api.openai.com/v1/responses', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model,
        reasoning: { effort: economyLongform ? 'medium' : 'low' },
        instructions,
        input: [{
          role: 'user',
          content: [
            { type: 'input_text', text: contentText },
            { type: 'input_image', image_url: `data:${mimeType};base64,${imageBase64}` }
          ]
        }],
        text: {
          format: {
            type: 'json_schema',
            name: 'tracker_image_qc',
            strict: true,
            schema: QC_SCHEMA
          }
        }
      })
    })

    const raw = await response.text()
    let data: any = {}
    try { data = raw ? JSON.parse(raw) : {} } catch {}

    if (!response.ok) {
      return res.status(response.status).json({
        error: { message: data?.error?.message || raw || 'OpenAI image QC request failed' }
      })
    }

    const text = extractText(data)
    if (!text) return res.status(502).json({ error: { message: 'OpenAI image QC response had no text output' } })

    let result: any
    try { result = JSON.parse(text) }
    catch {
      return res.status(502).json({ error: { message: 'OpenAI image QC response was not valid JSON' } })
    }

    const economyHardGate = economyLongform && Boolean(
      result?.defects?.mascotMissingOrWrongCount ||
      result?.defects?.styleFloorFailure ||
      result?.defects?.wrongOrientation
    )
    if (economyHardGate) result.decision = 'RETRY'

    console.log('[GPT_IMAGE_QC]', JSON.stringify({
      decision: result?.decision,
      semanticMatch: result?.semanticMatch,
      defects: result?.defects,
      confidence: result?.confidence,
      economyLongform
    }))

    return res.status(200).json({
      ok: true,
      ...result,
      provider: 'OpenAI',
      model,
      contractVersion: 'gpt-vision-qc-v1.1',
      usage: data?.usage || null
    })
  } catch (error: any) {
    return res.status(500).json({ error: { message: error?.message || String(error) } })
  }
}